spring:
  application:
    name: sync-admin-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  datasource:
    url: jdbc:h2:file:./data/sync-admin;MODE=MySQL;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  health:
    mongo:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,logfile

logging:
  file:
    path: ./logs

server:
  port: 8080
